config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  devise_for :users

  resources :users do
    # nested resource for job_applications
    resources :job_applications, only: [:show, :index]
  end

  resources :jobs, :categories, :job_applications

  get '/dashboard' => 'jobs#dashboard'
end

app/models/job.rb
class Job < ApplicationRecord
  include Sortable::InstanceMethods
  extend Sortable::ClassMethods

  validates_presence_of :title, :description, :company_name, :location, :category_id
  belongs_to :company, :class_name => 'User', :foreign_key => 'company_id'
  belongs_to :category
  has_many :job_applications, :dependent => :destroy
  has_many :applicants, :through => :job_applications, :class_name => 'User'
  has_many :jobs_skills
  has_many :skills, :through => :jobs_skills
  accepts_nested_attributes_for :skills


  def self.by_category(category_id)
    where(category: category_id)
  end

  def self.by_location(location_name)
    where(location: location_name)
  end

  def self.by_location_and_category(category_id, location_name)
    self.by_category(category_id).by_location(location_name)
  end

  def self.all_sort_by_date_skip_first
    self.all_sort_by_date.limit(9)[1..-1]
  end

  def self.locations
    self.all.collect {|job| job.location}.uniq
  end

  def skills_attributes=(skill_attributes)
    skill_attributes.values.each do |skill_attribute|
      skill = Skill.find_or_create_by(skill_attribute)
      self.jobs_skills.build(skill: skill)
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index]

  def index
    @items_per_page = 100
    @latest_jobs = Job.all_sort_by_date_skip_first
    @locations = Job.locations
    @categories = Category.all

    # Filter by Category and Location
    if !params[:category].blank? && !params[:location].blank?
      @jobs = Job.by_location_and_category(params[:category], params[:location]).order_and_paginated(params[:page], @items_per_page)
      respond_to_html_and_json(@jobs)

    # Filter by Category Only
    elsif !params[:category].blank?
      @jobs = Job.by_category(params[:category]).order_and_paginated(params[:page], @items_per_page)
      respond_to_html_and_json(@jobs)

    # Filter by Location Only
    elsif !params[:location].blank?
      @jobs = Job.by_location(params[:location]).order_and_paginated(params[:page], @items_per_page)
      respond_to_html_and_json(@jobs)

    else
    # All Jobs
      @jobs = Job.order_and_paginated(params[:page], @items_per_page)
      respond_to_html_and_json(@jobs)
    end
  end

  def new
    @job = Job.new
    authorize @job
  end

  def show
    @jobs = Job.all_sort_by_date.page.limit(8)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @job}
    end
    authorize @job
  end

  def create
    @job = Job.new(job_params)
    authorize @job

    if @job.save
      redirect_to @job, alert: "Job offer succesfully created"
    else
      render new_job_path, alert: "Oops!, please try again!"
    end
  end

  def edit
    authorize @job
  end

  def update
    authorize @job
    @job.update(job_params)
    redirect_to @job, alert: "Job offer succesfully updated"
  end

  def dashboard
    if current_user.company?
      @jobs = current_user.jobs.order_and_paginated(params[:page], 5)
      @latest_jobs = Job.all_sort_by_date.limit(9)
    else
      redirect_to root_path, alert: "You are not authorized to see that page."
    end
  end

  def destroy
    authorize @job
    @job.destroy
    redirect_to root_path, alert: "Job offer succesfully deleted"
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :company_name ,:url, :location, :category_id, :company_id, skill_ids:[], skills_attributes:[:name])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <%= bootstrap_form_for @job do |f| %>

      <% if current_user.errors.any? %>
          <div id="error_explanation" class="errors">
            <ul>
            <% current_user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.text_field :title, placeholder: "Title Here...", label: "Title* (Required)" %>
        <%= f.text_field :company_name, placeholder: "Company Name Here...", label: "Company Name* (Required)" %>
        <%= f.text_area :description, placeholder: "Add a description Here...", label: "Description* (Required)" %>
        <%= f.text_field :location, placeholder: "Location Here...", label: "location* (Required)" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Select Category', label: "Category* (required)"%>
        <%= f.label "Skills Needed" %>
        <%= f.collection_check_boxes :skill_ids, Skill.all, :id, :name, label: (fa_icon 'cogs-o 2x') %>
        <%= f.fields_for :skills, @job.skills.build do |skills_fields| %>
          <%= skills_fields.text_field :name, label: "Another Skill (Optional)", placeholder: "Add a new skill here..." %>
        <% end %>
        <%= f.url_field :url, placeholder: "http://...", label: "Url (Optional) - Must start with http://" %>
        <%=  f.hidden_field :company_id, :value => current_user.id unless @job.company_id %>
        <%= f.submit class: "btn btn-primary btn-outline btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/dashboard.html.erb
<div class="col-sm-3">
  <div class="panel panel-default filter">
    <div class="panel-heading">Dashboard</div>
    <div class="panel-body">
    <%= link_to "Edit My Account", edit_user_registration_path(current_user) %>
    </div>
  </div>

  <%if current_user %>
  <div class="panel panel-default filter">
    <div class="panel-heading"><%= fa_icon 'briefcase' %> My Activity</div>
    <div class="panel-body">
      <% if current_user.user? %>
        <%= link_to "My Applications", user_job_applications_path(current_user) if current_user%>
      <% elsif current_user.company? %>
        <%= link_to "My Job Offers", dashboard_path %>
      <% end %>
    </div>
  </div>
  <% end %>
</div> <!-- End col-sm-3 -->

<div class="col-sm-6">
  <% if @jobs.empty? %>
    <h1>Sorry, no jobs found.</h1>
  <% else %>
    <% @jobs.each do |job| %>
    <div class="well">
      <h4><%= link_to job.title, job_path(job)%></h4>
      <small><%= job.company_name %> | <%= job.posting_date %> | <%= fa_icon "map-marker" %> <%= job.location %> </small>
      <h4>Applicants</h4>
      <ol>
        <% job.applicants.each do |applicant| %>
          <li><%= mail_to(applicant.email) %></li>
        <% end %>
      </ol>
    </div>
  <% end %>
  <% end %>
  <%= paginate @jobs %>
</div> <!-- end col-sm-6 -->

app/views/jobs/edit.html.erb
<h1>Edit Job Offer <%= fa_icon "pencil"%></h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<div class="col-sm-3">
  <div class="panel panel-default filter">
    <div class="panel-heading">Filter Jobs</div>
    <div class="panel-body filter-form-wrap">
      <%= bootstrap_form_tag url: '/jobs', method: 'get' do %>
        <%= select_tag "category", options_from_collection_for_select(@categories, "id", "name"), include_blank: "Select Category", class: "btn btn-default dropdown-toggle category"%>
        <%= select_tag "location", options_for_select(@locations), include_blank: "Select Location", class: "btn btn-default dropdown-toggle location"%>
        <%= submit_tag "Filter", class: "btn btn-primary btn-outline btn-sm filter" %>
      <% end %>
    </div>
  </div>

  <%if current_user %>
  <div class="panel panel-default filter">
    <div class="panel-heading"><%= fa_icon 'briefcase' %> My Account</div>
    <div class="panel-body">
      <% if current_user.user? %>
        <%= link_to "My Applications", user_job_applications_path(current_user) if current_user%>
      <% elsif current_user.company? %>
        <%= link_to "My Job Offers", dashboard_path %>
      <% elsif current_user.admin? %>
      <ul>
        <li><%= link_to "Job Applications", job_applications_path %></li>
        <li><%= link_to "Categories", categories_path %></li>
      </ul>
      <% end %>
    </div>
  </div>
  <% end %>
</div> <!-- End col-sm-3 -->

<div class="col-sm-8 results">
  <% if @jobs.empty? %>
    <h1>Sorry, no jobs found.</h1>
  <% else %>
    <% @jobs.each do |job| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= link_to job.title, job_path(job)%></h3>
        <small><%= job.company_name %> | <%= job.posting_date %> | <%= fa_icon "map-marker" %> <%= job.location %> </small>
        <p><%= truncate(job.description, length: 150) %></p>
      </div>
    </div>
    <% end %>
  <% end %>
  <%= paginate @jobs %>
</div> <!-- end col-sm-6 -->

<!-- AJAX Filter Script -->
<script type="text/javascript">
$(function () {
  // Listener on click function
  $("input.filter").on('click', function(event) {
    var html = ''
    var category = $(".category").val();
    var loc = $(".location").val().split(" ").join("+")
    var url = "/jobs?utf8=✓&category=" + category + "&location=" + loc + "&commit=Filter"
    // AJAX
    $.getJSON(url, function(jobs) {
      // Check if there are any results
      if (jobs.length == 0) {
        // Display nothing found message
        html += '<h1>Sorry, no jobs found.</h1>'
      } else {
        $.each(jobs, function(i, job) {
          // create a js Job Object using constructor
          var newJob = new Job (job.id, job.title, job.description, job.company_name, job.url, job.location, job.created_at, job["category"]["name"])
          // Create HTML
          html += '<div class="panel panel-default">'
          html += ' <div class="panel-body">'
          html += '<h3><a href="/jobs/' + newJob.id + '">' + newJob.title + '</a></h3>'
          html += '<small>' + newJob.companyName + ' | ' + newJob.createdAt() + ' | <i class="fa fa-map-marker"></i> ' + newJob.location + ' </small>'
          html += '<p>' + newJob.description.substring(0,150) + '...' + '</p>'
          html += ' </div>'
          html +='</div>'
        });
      }
      // Clear results div
      $('.results').empty();
      // Add HTML to the DOM
      $('.results').append(html);
    })
    event.preventDefault();
  });

  // Job Object Constructor Function
  function Job (id, title, description, companyName, url, location, created_at, category) {
    this.id = id;
    this.title = title;
    this.description = description;
    this.companyName = companyName;
    this.url = url;
    this.location = location;
    this.created_at = created_at;
    this.category = category;

    // Format created_at attribute function
    this.createdAt = function() {
      var monthNames = new Array("January", "February", "March",
      "April", "May", "June", "July", "August", "September",
      "October", "November", "December");
      var date = new Date(this.created_at);
      var day = date.getDate();
      var monthFormat = date.getMonth();
      var year = date.getFullYear();
      return monthNames[monthFormat].slice(0,3) + " " + day + "," + year
    };
  }
});
</script>

app/views/jobs/new.html.erb
<h1>Create a new Job Offer <%= fa_icon "pencil"%></h1>

<%= render 'form' %>

app/views/jobs/show.html.erb
<div class="row">

  <div class="col-sm-9">
    <div class="well">
      <h1><%= @job.title %></h1>
      <small>Posted: <%= @job.posting_date %></small>
      <h4><span class="label label-default"><%= @job.category.name %></span></h4>
      <h3>Company:</h3>
      <p><%= fa_icon "industry" %> <%= @job.company_name.capitalize %> | <%= fa_icon "map-marker" %> <%= @job.location %></p>
      <h4>Description:</h4>
      <p><%= @job.description %></p>
      <h5>Company Url: <%= link_to @job.url, "http://#{@job.url}" %></h5>


      <div class="row">
        <div class="col-sm-6">
          <h4>Skills Required:</h4>
          <% @job.skills.each do |skill| %>
            <small><%= skill.name %> | </small>
          <% end %>
        </div>
      </div>

        <div class="row">
        <% if current_user.user? %>
          <div class="col-sm-2 pull-right">
            <%= link_to "Apply", new_job_application_path(job_id: @job.id, user_id: current_user), class: "btn btn-primary btn-outline btn-md" %>
          </div>
        <% elsif policy(@job).update? %>
          <div class="col-sm-2 pull-right">
            <%= button_to "Edit", edit_job_path, method: "get", class: "btn btn-success btn-outline btn-md" %>
          </div>
          <div class="col-sm-2 pull-right">
            <%= button_to "Delete", job_path, method: "delete", class: "btn btn-danger btn-outline btn-md" %>
          </div>
        <% end %>
      </div>
    </div>
    <%= button_to "Back", jobs_path, method: "get", class: "btn btn-primary btn-outline btn-sm" %>
  </div>

</div>