config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  devise_for :users

  resources :users do
    # nested resource for job_applications
    resources :job_applications, only: [:show, :index]
  end

  resources :jobs, :categories, :job_applications

  get '/dashboard' => 'jobs#dashboard'
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  include Sortable::InstanceMethods
  extend Sortable::ClassMethods
  
  belongs_to :job
  belongs_to :applicant, :class_name => 'User', :foreign_key => 'user_id'
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, :except => [:index, :new, :create]

  def index
    @items_per_page = 9
    @latest_jobs = Job.all_sort_by_date_skip_first

    if params[:user_id] || current_user.user?
      @job_applications = current_user.job_applications.order_and_paginated(params[:page], @items_per_page)
    elsif current_user.admin?
      @job_applications = JobApplication.order_and_paginated(params[:page], @items_per_page)
    end
  end

  def new
    @job_application = JobApplication.new
    authorize @job_application
  end

  def create

    @job_application = JobApplication.find_by_user_id_and_job_id(params[:job_application][:user_id], params[:job_application][:job_id])

    if !@job_application.nil?
      redirect_to root_path, alert: "You already applied for this job."
    else
      @job_application = JobApplication.new(job_application_params)
      authorize @job_application
      if @job_application.save
        redirect_to root_path, alert: "Your application has been sent. Good Luck!"
      else
        render_to new_job_application_path, alert: "Oops, there was a problem, please try again"
      end
    end
  end

  def show
    authorize @job_application
    @jobs = Job.all_sort_by_date.limit(8)
  end

  def edit
    authorize @job_application
  end

  def update
    authorize @job_application
  end

  def destroy
    authorize @job_application
    @job_application.destroy
    redirect_to root_path
  end

  private
  def set_job_application
    @job_application = JobApplication.find(params[:id])
  end

  def job_application_params
    params.require(:job_application).permit(:user_id, :job_id, :message, :years_of_experience)
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper

  def current_job
    job = Job.find(params[:job_id])
  end
end

app/views/job_applications/_form.html.erb
<%= bootstrap_form_for(@job_application) do |f| %>

  <%= f.hidden_field :user_id, :value => params[:user_id] %>
  <%= f.hidden_field :job_id, :value => params[:job_id] %>
  <div class="row">
    <div class="col-sm-3">
      <%= f.number_field :years_of_experience %>
    </div>
  </div>
  <%= f.text_area :message, label: "Tell us about your self"  %>

  <div class="row">
    <%= f.submit "Send Application", class: "btn btn-primary btn-outline btn-sm pull-right" %>
  </div>
<% end %>

app/views/job_applications/index.html.erb
<div class="col-sm-9">
  <% if @job_applications.empty? %>
    <h1>You dont have any applications.</h1>
  <% else %>
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Applications</h3></div>
    <div class="panel-body">
      <% @job_applications.each do |application| %>
        <% if current_user.admin? %>
          <li><%= link_to application.job.title, job_path(application.job)%> <small>Applied on <%= application.posting_date%></small></li>
        <% else %>
          <li><%= link_to application.job.title, user_job_application_path(current_user, application)%> <small>Applied on <%= application.posting_date%></small></li>
        <% end %>
        <%= fa_icon 'industry' %> <%= application.job.company_name %> | <%= application.job.category.name %>
        <% if current_user.admin? %>
          <li>Applicant: <%= application.applicant.email %></li>
        <% end %>
        <br></br>
      <% end %>
    </div>
  </div>
  <% end %>
  <%= paginate @job_applications %>
</div> <!-- end col-sm-6 -->

app/views/job_applications/new.html.erb
<div class="col-sm-8">
  <h1>Apply for this Job <%= fa_icon "pencil" %></h1>

  <div class="well">
    <h3><%= current_job.title %></h3>
    <h4><%= fa_icon "industry" %> <%= current_job.company_name.capitalize %> | <%= fa_icon "map-marker" %> <%= current_job.location %></h4>
    <p><%= current_job.description %></p>
    <%= render 'form' %>
  </div>
</div>

app/views/job_applications/show.html.erb
<div class="col-sm-9">
  <div class="well">
    <h1><%= @job_application.job.title %></h1>
    <small>Posted: <%= @job_application.job.posting_date %></small>
    <h4><span class="label label-default"><%= @job_application.job.category.name %></span></h4>
    <h3>Company:</h3>
    <p><%= fa_icon "industry" %> <%= @job_application.job.company_name.capitalize %> | <%= fa_icon "map-marker" %> <%= @job_application.job.location %></p>
    <h4>Description:</h4>
    <p><%= @job_application.job.description %></p>
    <h5>Company Url: <%= link_to @job_application.job.url, "http://#{@job_application.job.url}" %></h5>


    <div class="row">
      <div class="col-sm-6">
        <h4>Skills Required:</h4>
        <% @job_application.job.skills.each do |skill| %>
          <small><%= skill.name %> | </small>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to "Back", 'javascript:history.go(-1);', class: "btn btn-primary btn-outline btn-sm" %>
</div>