config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  devise_for :users

  resources :users do
    # nested resource for job_applications
    resources :job_applications, only: [:show, :index]
  end

  resources :jobs, :categories, :job_applications

  get '/dashboard' => 'jobs#dashboard'
end

app/models/category.rb
class Category < ApplicationRecord
  include Sortable::InstanceMethods
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :jobs
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, :except => [:index, :new, :create]

  def index
    @categories = Category.all
    respond_to_html_and_json(@categories)
  end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    if @category.save
      redirect_to categories_path, alert: "Category #{@category.name} has been created"
    else
      render_to new_category_path
    end
  end

  def show
    authorize @category
    respond_to do |format|
      format.html {render :show }
      format.json {render json: @category}
    end
  end

  def edit
    authorize @category
  end

  def update
    @category.update(category_params)
    redirect_to category_path, alert: "This category has been updated"
  end

  def destroy
    authorize @category
    @category.destroy
    redirect_to root_path, alert: "Category #{@category.name} has been deleted"
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for @category do |f| %>
  <%= f.text_field :name %><br></br>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<div class="col-sm-4">
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Categories</h3>
    </div>
    <div class="panel-body">
      <% @categories.each do |category| %>
      <ul>
        <li><%= link_to category.name, category_path(category) %></li>
      </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="col-sm-8">
<% if current_user.admin? %>
  <%= link_to (fa_icon 'plus').to_s + "  Add New Category", new_category_path, class: "btn btn-primary btn-outline btn-md" %>
<% end %>
</div>

app/views/categories/new.html.erb
<h1>Create Category</h1>

<div class="col-sm-4">
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p>Created: <%= @category.posting_date %></p>

<% if policy(@category).update? %>
  <p><%= button_to "Edit", edit_category_path, method: "get", class: "btn btn-success btn-outline btn-md" %></p>
  <p><%= button_to "Delete", category_path, method: "delete", class: "btn btn-danger btn-outline btn-md" %></p>
  <p><%= link_to "Go to Categories", categories_path, class: "btn btn-primary btn-outline btn-md" %></p>
<% end %>