config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  devise_for :users

  resources :users do
    # nested resource for job_applications
    resources :job_applications, only: [:show, :index]
  end

  resources :jobs, :categories, :job_applications

  get '/dashboard' => 'jobs#dashboard'
end

app/views/layouts/_messages.html.erb
<% if flash[:error] %>
  <div id="notice_wrapper">
    <p><%= flash[:error] %></p>
  </div>
<% elsif flash[:notice] %>
  <div id="notice_wrapper">
    <p><%= flash[:notice] %></p>
  </div>
<% elsif flash[:alert] %>
  <div id="notice_wrapper">
    <p><%= flash[:alert] %></p>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
  <div class="header-inner">
    <h1><%= link_to (fa_icon 'code').to_s + "TechJobs", root_path %></h1>
    <nav role="navigation">
      <ul>
        <% if !current_user %>
            <li class="cta"><%= link_to "Sign up", new_user_registration_path %></li>
            <li class="cta"><%= link_to "Log in", new_user_session_path %></li>
        <% elsif current_user.company? %>
          <li><%= fa_icon 'user' %> logged in as: <%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to "My Job Offers", dashboard_path %></li>
          <li class="cta"><%= link_to "Post a Job Offer", new_job_path %></li>
          <li class="cta"><%= link_to (fa_icon 'power-off') + "  Log out", destroy_user_session_path, :method => 'delete' %></li>
        <% else %>
          <li><%= fa_icon 'user' %> logged in as: <%= link_to current_user.email, edit_user_registration_path %></li>
          <li class="cta"><%= link_to "My Job Applications", job_applications_path unless current_user.admin? %></li>
          <li class="cta"><%= link_to (fa_icon 'power-off') + "  Log out", destroy_user_session_path, :method => 'delete' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobs</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header id="fh5co-header" role="banner">
      <%= render 'layouts/messages' %>
      <%= render 'layouts/navigation' %>
    </header>

  <div class="container main" id="main" >

    <%= yield %>
  </div>
  <footer id="fh5co-footer" role="contentinfo">

		<div class="container">

			<div class="col-md-12 fh5co-copyright text-center">
        <p>&copy; 2019 All Rights Reserved </p>
			</div>

		</div>
	</footer>

  </body>
</html>